sudo: required

services:
  - docker
before_install:
  - docker build -t tuanminh009/client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true tuanminh009/client-test npm run test -- --coverage
after_success:
  - docker build -t tuanminh009/mutil-client ./client
  - docker build -t tuanminh009/mutil-server ./server
  - docker build -t tuanminh009/mutil-nginx ./nginx
  - docker build -t tuanminh009/mutil-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tuanminh009/mutil-client 
  - docker push tuanminh009/mutil-server 
  - docker push tuanminh009/mutil-nginx
  - docker push tuanminh009/mutil-worker 
deploy:
  provider: elasticbeanstalk
  app: mutil-docker
  region: us-east-1
  env:  Mutildocker-env
  bucket_path: mutil-docker
  bucket: elasticbeanstalk-us-east-1-225317789430
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY