version: '3'
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=vutuanminh
  redis-server:
    image: "redis:latest"
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
  server-api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_DATABASE_NAME=postgres
      - PG_USER=postgres
      - PG_PASSWORD=vutuanminh
      - PG_PORT=5432
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    environment:
      - WDS_SOCKET_PORT=0