version: '3'
services:
  client:
    image: tuanminh009/mutil-client
    mem_limit: 128m
    hostname: client
  server:
    image: tuanminh009/mutil-server
    mem_limit: 128m
    hostname: server-api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_HOST=$PG_HOST
      - PG_DATABASE_NAME=$PG_DATABASE_NAME
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
  worker:
    image: tuanminh009/mutil-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx: 
    image: tuanminh009/mutil-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - 80:80